const $ = s => document.querySelector(s);
const token = new URLSearchParams(location.search).get('id');
let project = null;
let business = null;
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = (n,c='GHS') => { try { return new Intl.NumberFormat('en-GH',{style:'currency',currency:c,maximumFractionDigits:2}).format(Number(n||0)); } catch { return `${c} ${Number(n||0).toFixed(2)}`; } };
const date = x => x ? new Date(x).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'}) : '';
async function api(action, body, method='POST'){
  const options={method:body?method:'GET',headers:{'x-project-token':token}};
  if(body){options.headers['content-type']='application/json';options.body=JSON.stringify(body)}
  const r=await fetch(`/.netlify/functions/api?action=${encodeURIComponent(action)}`,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Something went wrong.');return d;
}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2800)}
function showError(msg){$('#loadingState').classList.add('hidden');$('#errorState').classList.remove('hidden');$('#errorText').textContent=msg}
function setBusiness(){if(!business)return;$('#brandName').textContent=business.businessName||'JVO';$('#footerBrand').textContent=business.businessName||'JVO';$('#footerContact').textContent=[business.ownerName,business.phone,business.email].filter(Boolean).join(' · ')}
function statusProgress(status){const steps=[['Agreement','Agreement Sent','Awaiting Deposit'],['Payment','Deposit Received'],['Build','Development'],['Review','Client Review','Approved','Awaiting Final Payment'],['Paid','Fully Paid'],['Launch','Launched','Completed']];const order=['Draft','Agreement Sent','Agreement Signed','Awaiting Deposit','Deposit Received','Development','Client Review','Approved','Awaiting Final Payment','Fully Paid','Launched','Completed'];const idx=order.indexOf(status);return `<div class="progress-track">${steps.map((s,i)=>{const max=Math.max(...s.slice(1).map(x=>order.indexOf(x)));const min=Math.min(...s.slice(1).map(x=>order.indexOf(x)).filter(x=>x>=0));const cls=idx>max?'done':idx>=min?'current':'';return `<div class="progress-step ${cls}">${esc(s[0])}</div>`}).join('')}</div>`}
function renderAgreement(){
  $('#projectRef').textContent=project.ref||'';$('#projectName').textContent=project.projectName||'';$('#projectTotal').textContent=money(project.total,project.currency);$('#projectStatus').textContent=project.status||'Draft';$('#projectTimeline').textContent=project.timeline||'To be agreed';$('#projectScope').textContent=project.scope||'';
  $('#projectFeatures').innerHTML=(project.features||[]).map(x=>`<span>${esc(x)}</span>`).join('');
  $('#paymentPlan').innerHTML=(project.paymentPlan?.milestones||[]).map(m=>`<div class="plan-row"><strong>${esc(m.label)}</strong><p>${m.percent}% · ${money(m.amount,project.currency)}</p></div>`).join('')||'<p class="muted">Payment plan will be confirmed by JVO.</p>';
  $('#termsVersion').textContent=project.termsVersion?`Terms ${project.termsVersion}`:'';
  $('#termsList').innerHTML=(project.terms||[]).map(t=>`<div class="term"><strong>${esc(t.title)}</strong><p>${esc(t.body)}</p></div>`).join('');
}
function renderPortal(){
  const signed=!!project.signedAt;if(!signed)return;
  $('#signSection').classList.add('hidden');$('#portalProgress').classList.remove('hidden');$('#portalProgress').innerHTML=statusProgress(project.status);
  $('#introTitle').innerHTML='Your project,<br><em>all in one place.</em>';$('#introCopy').textContent='Your signed agreement, payments, updates and next steps stay on this page.';
  $('#signedPanel').classList.remove('hidden');$('#signedBy').textContent=`Signed by ${project.clientName||'client'}`;$('#signedMeta').textContent=`Signed ${date(project.signedAt)}. This signed version does not change if the project is edited later.`;$('#agreementPdf').href=`/.netlify/functions/api?action=agreementPdf&id=${encodeURIComponent(token)}`;
  $('#paymentSection').classList.remove('hidden');const f=project.financials||{};$('#outstandingAmount').textContent=f.outstanding>0?`${money(f.outstanding,project.currency)} due`:'Paid';
  $('#financialGrid').innerHTML=[['Contract',f.contract],['Approved extras',f.extras],['Paid',f.paid],['Outstanding',f.outstanding]].map(([l,v])=>`<div><span>${l}</span><strong>${money(v,project.currency)}</strong></div>`).join('');
  if(f.outstanding>0 && (project.paymentInstructions||project.paymentLink)){ $('#paymentInstructionsWrap').classList.remove('hidden');$('#paymentInstructions').textContent=project.paymentInstructions||'';if(project.paymentLink){$('#paymentLink').href=project.paymentLink;$('#paymentLink').classList.remove('hidden')} }
  $('#paymentHistory').innerHTML=(project.payments||[]).length?project.payments.slice().reverse().map(p=>`<div class="record"><div><h3>${esc(p.type||'Payment')}</h3><p>${esc(p.method||'')} ${p.date?`· ${esc(date(p.date))}`:''}<br>${esc(p.receiptNo||'')}</p></div><div class="record-side"><strong>${p.direction==='out'?'-':''}${money(p.amount,p.currency)}</strong><div class="record-actions"><a class="tiny-link" href="/.netlify/functions/api?action=receiptPdf&id=${encodeURIComponent(token)}&payment=${encodeURIComponent(p.id)}" target="_blank" rel="noreferrer">Receipt PDF</a></div></div></div>`).join(''):'<p class="muted">No payments have been recorded yet.</p>';
  const changes=project.changeOrders||[];if(changes.length){$('#changesSection').classList.remove('hidden');$('#changeOrders').innerHTML=changes.map(c=>`<div class="record"><div><h3>${esc(c.description)}</h3><p>Status: ${esc(c.status)}</p>${c.status==='Quoted'?`<div class="decision-row"><button class="approve" data-change="${c.id}" data-decision="Approved">Approve</button><button data-change="${c.id}" data-decision="Declined">Decline</button></div>`:''}</div><div class="record-side"><strong>${money(c.amount,c.currency)}</strong></div></div>`).join('');document.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>changeDecision(b));}
  if(['Client Review','Approved','Awaiting Final Payment'].includes(project.status)){ $('#reviewSection').classList.remove('hidden'); }
  const updates=project.updates||[];if(updates.length){$('#updatesSection').classList.remove('hidden');$('#updates').innerHTML=updates.map(u=>`<div class="update"><time>${esc(date(u.createdAt))}</time><p>${esc(u.message)}</p></div>`).join('')}
  if(project.liveUrl && ['Launched','Completed'].includes(project.status)){ $('#liveSection').classList.remove('hidden');$('#liveUrl').href=project.liveUrl; }
}
async function changeDecision(button){button.disabled=true;try{await api('changeOrderDecision',{changeId:button.dataset.change,decision:button.dataset.decision});toast(`Additional work ${button.dataset.decision.toLowerCase()}.`);await load()}catch(e){toast(e.message)}finally{button.disabled=false}}
function fieldError(input,msg){const f=input.closest('.field');f?.classList.toggle('invalid',!!msg);const s=f?.querySelector('.field-error');if(s)s.textContent=msg||''}
function validate(form){let ok=true;['fullName','email','phone','signature'].forEach(n=>{const i=form.elements[n];let msg='';if(!i.value.trim())msg='This field is required.';if(n==='email'&&i.value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(i.value))msg='Enter a valid email address.';fieldError(i,msg);if(msg)ok=false});if(form.elements.signature.value.trim().toLowerCase()!==form.elements.fullName.value.trim().toLowerCase()){fieldError(form.elements.signature,'Signature must match the full name above.');ok=false}form.querySelectorAll('input[type=checkbox]').forEach(i=>{if(!i.checked)ok=false});if(!ok&&!form.querySelector('input[type=checkbox]:not(:checked)'))return ok;if(form.querySelector('input[type=checkbox]:not(:checked)'))toast('Please accept all four confirmations.');return ok}
$('#agreementForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;if(!validate(form))return;const btn=$('#signButton');btn.disabled=true;btn.classList.add('loading');const fd=new FormData(form);const accepted=['confirm_scope','confirm_extra','confirm_payment','confirm_terms'].filter(k=>fd.get(k));const body={fullName:fd.get('fullName'),email:fd.get('email'),phone:fd.get('phone'),company:fd.get('company'),signature:fd.get('signature'),acceptedCheckboxes:accepted};try{await api('sign',body);toast('Agreement signed.');await load();$('#signedPanel').scrollIntoView({behavior:'smooth',block:'center'})}catch(err){toast(err.message)}finally{btn.disabled=false;btn.classList.remove('loading')}});
$('#reviewForm').addEventListener('submit',async e=>{e.preventDefault();const submitter=e.submitter;const decision=submitter?.value;if(!decision)return;submitter.disabled=true;try{await api('clientDecision',{decision,message:new FormData(e.currentTarget).get('message')});toast(decision==='approve'?'Website approved.':'Changes sent to JVO.');await load()}catch(err){toast(err.message)}finally{submitter.disabled=false}});
async function load(){if(!token){showError('This project link is missing its ID.');return}try{const d=await api('publicProject',null,'GET');project=d.project;business=d.business;setBusiness();renderAgreement();renderPortal();$('#loadingState').classList.add('hidden');$('#errorState').classList.add('hidden');$('#app').classList.remove('hidden')}catch(e){showError(e.message)}}
load();
