const $=s=>document.querySelector(s);const qs=new URLSearchParams(location.search);const token=qs.get('id');let project=null;
const money=(n,c='GHS')=>new Intl.NumberFormat('en-GH',{style:'currency',currency:c||'GHS',maximumFractionDigits:2}).format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(action,options={}){const r=await fetch(`/.netlify/functions/api?action=${encodeURIComponent(action)}`,options);const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Something went wrong.');return data}
function terms(p){const support=p.supportDays||30;return[
 ['Payment',`50% is required before work starts. The other 50% is due after you approve the finished site.`],
 ['When work starts','Work officially starts only after this agreement is signed and the deposit is received.'],
 ['Deposit','The deposit is not refundable once development has started.'],
 ['Extra work','The price covers only the scope shown above. New pages, features, integrations or other additions can be priced separately before I add them.'],
 ['Bug support',`For ${support} days after launch, JVO will fix broken layouts or broken code caused by the original setup at no extra cost.`],
 ['Third-party issues','Free support does not cover hosting problems, external APIs, payment gateway changes, plugin updates or expired domains.'],
 ['Final payment','The site will only be launched, transferred or handed over after full payment is received.'],
 ['Ownership','Ownership of the finished work moves to you after full payment. JVO can still show the finished site in its portfolio and promotional work.'],
 ['Your content','You are responsible for the text, images, logos and other content you provide. You confirm that you have permission to use them.'],
 ['Delays','If content, access details or approvals are delayed, the delivery date may also move.'],
 ['Late balance','A final payment that stays unpaid for more than 7 days may cause JVO-managed access or services to be paused until payment is made.'],
 ['Cancellation','If you cancel after work starts, the deposit is kept. Any completed work above the deposit value must also be paid before files are handed over. If JVO cancels, unearned fees are refunded.']
]}
async function load(){if(!token){showError('This project link is missing its ID.');return}try{const d=await api('publicProject',{headers:{'x-project-token':token}});project=d.project;$('#projectRef').textContent=project.ref||'';$('#projectName').textContent=project.projectName;$('#projectTotal').textContent=money(project.total,project.currency);$('#projectDeposit').textContent=money(project.deposit,project.currency);$('#projectBalance').textContent=money(project.balance,project.currency);$('#projectTimeline').textContent=project.timeline||'To be agreed';$('#projectSupport').textContent=`${project.supportDays||30} days`;$('#projectScope').textContent=project.scope||'';$('#projectFeatures').innerHTML=(project.features||[]).map(x=>`<span>${esc(x)}</span>`).join('');$('#termsList').innerHTML=terms(project).map(([h,p])=>`<div class="term"><strong>${h}</strong><p>${p}</p></div>`).join('');$('#loadingState').classList.add('hidden');$('#agreementApp').classList.remove('hidden');if(project.signedAt)showSigned();}catch(e){showError(e.message)}}
function showError(msg){$('#loadingState').classList.add('hidden');$('#errorState').classList.remove('hidden');$('#errorText').textContent=msg}
function showSigned(){document.querySelectorAll('.paper-section').forEach(x=>x.classList.add('hidden'));$('#signedState').classList.remove('hidden');$('#signedDeposit').textContent=money(project.deposit,project.currency);$('#paymentInstructions').textContent=project.paymentInstructions||'James will send you the payment details.';if(project.paymentLink){$('#paymentLink').href=project.paymentLink;$('#paymentLink').classList.remove('hidden')}$('#signedState').scrollIntoView({behavior:'smooth',block:'center'})}
$('#agreementForm')?.addEventListener('submit',async e=>{e.preventDefault();const btn=$('#signButton');const fd=new FormData(e.currentTarget);if(fd.get('signature').trim().toLowerCase()!==fd.get('fullName').trim().toLowerCase()){alert('Please type the same full name in the signature box.');return}btn.disabled=true;btn.firstChild.textContent='Signing... ';try{await api('sign',{method:'POST',headers:{'content-type':'application/json','x-project-token':token},body:JSON.stringify(Object.fromEntries(fd))});project.signedAt=new Date().toISOString();showSigned()}catch(err){alert(err.message)}finally{btn.disabled=false;btn.firstChild.textContent='Sign and accept '}});load();
