import { JVO_RESTAURANT_TEMPLATE, JVO_RESTAURANT_EMAIL_TEMPLATE } from './restaurant-studio-data.js?v=20261004-final9';

const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]));
const arrowIcon = '<svg class="studio-arrow" viewBox="0 0 16 16" aria-hidden="true"><path d="M3.5 12.5 12.5 3.5M6.5 3.5h6v6"/></svg>';
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
const repoImages = () => Object.values(window.JVO_REPO_IMAGES || {});
const defaultTemplate = () => JSON.parse(JSON.stringify(window.JVO_RESTAURANT_TEMPLATE || JVO_RESTAURANT_TEMPLATE));
const defaultEmail = () => JSON.parse(JSON.stringify(window.JVO_RESTAURANT_EMAIL_TEMPLATE || JVO_RESTAURANT_EMAIL_TEMPLATE));
const getImageSrc = img => img?.source === 'cloudinary' ? img.url : img?.source === 'url' ? img.url : img?.source === 'repo' ? window.JVO_REPO_IMAGES?.[img.id]?.url || window.JVO_REPO_IMAGES?.[window.JVO_LEGACY_IMAGE_ALIASES?.[img.id]]?.url || '' : '';
const slugPreview = name => String(name || 'restaurant').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,65) || 'restaurant';
const siteDemoUrl = slug => `${location.origin}${location.hostname === 'localhost' || location.hostname === '127.0.0.1' ? `/restaurant-demo.html?slug=${encodeURIComponent(slug)}` : `/restaurant/${encodeURIComponent(slug)}`}`;
const modal = () => document.querySelector('#modal');
const modalBody = () => document.querySelector('#modalBody');
function openModal(html) { modalBody().innerHTML = html; modal().classList.remove('hidden'); document.body.classList.add('modal-open'); setTimeout(() => modalBody().querySelector('input,textarea,select,button')?.focus(), 20); }
function closeModal() { modal().classList.add('hidden'); document.body.classList.remove('modal-open'); modalBody().innerHTML = ''; }
function toast(msg) { const text = document.querySelector('#toastText'); const box = document.querySelector('#toast'); text.textContent = msg; box.classList.add('show'); clearTimeout(toast.t); toast.t = setTimeout(() => box.classList.remove('show'), 3000); }
function busy(btn,on,label='Working') { if (!btn) return; btn.disabled=on; btn.classList.toggle('loading',on); const span=btn.querySelector('.button-label'); if(span){ if(on){btn.dataset.oldLabel=span.textContent; span.textContent=label;} else span.textContent=btn.dataset.oldLabel||span.textContent; } }
function notifyError(err) { toast(err?.message || 'Something went wrong.'); console.error(err); }
function field(label,name,value,extra='') { return `<label class="field"><span>${esc(label)}</span><input name="${esc(name)}" value="${esc(value || '')}" ${extra}></label>`; }
function textarea(label,name,value,extra='') { return `<label class="field wide"><span>${esc(label)}</span><textarea name="${esc(name)}" ${extra}>${esc(value || '')}</textarea></label>`; }
function selectField(label,name,value,options) { return `<label class="field"><span>${esc(label)}</span><select name="${esc(name)}">${options.map(([v,t]) => `<option value="${esc(v)}" ${v===value?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`; }
function normalizeDemo(raw) {
  const d = JSON.parse(JSON.stringify(defaultTemplate()));
  return deepMerge(d, raw || {});
}
function deepMerge(target, source) { Object.entries(source || {}).forEach(([key,val]) => { if(val && typeof val==='object' && !Array.isArray(val) && target[key] && typeof target[key]==='object' && !Array.isArray(target[key])) deepMerge(target[key],val); else target[key]=val; }); return target; }
function imagePicker(name, current, acceptUpload=true) {
  const value = current || { source:'repo', id: repoImages()[0]?.id || '' };
  const preview = getImageSrc(value);
  const mode = value.source === 'cloudinary' ? 'cloudinary' : value.source === 'url' ? 'url' : 'repo';
  return `<div class="demo-media-field" data-media-field="${esc(name)}">
    <div class="media-preview">${preview ? `<img src="${esc(preview)}" alt="">` : '<div class="media-placeholder">No image yet</div>'}</div>
    <div class="media-controls">
      <div class="source-switch">
        <button type="button" data-source="repo" class="${mode==='repo'?'active':''}">Image library</button>
        <button type="button" data-source="url" class="${mode==='url'?'active':''}">Image URL</button>
        <button type="button" data-source="cloudinary" class="${mode==='cloudinary'?'active':''}">Upload</button>
      </div>
      <div class="repo-picker ${mode==='repo'?'':'hidden'}">${repoImages().map(img => `<button type="button" data-repo-id="${esc(img.id)}" class="repo-option ${value.id===img.id?'selected':''}" title="${esc(img.label)}"><img src="${esc(img.url)}" alt=""><span>${esc(img.label)}</span></button>`).join('')}</div>
      <div class="url-panel ${mode==='url'?'':'hidden'}">
        <div class="url-row"><input type="url" data-image-url-input value="${esc(value.url || '')}" placeholder="https://images.unsplash.com/..." inputmode="url"><button type="button" class="btn small dark" data-use-url>Use image</button></div>
        <p class="mini-note">Paste a direct image URL. Unsplash, Cloudinary and other https image URLs work.</p>
      </div>
      <div class="upload-panel ${mode==='cloudinary'?'':'hidden'}">
        <div class="upload-drop" tabindex="0" data-dropzone><strong>Drop an image here</strong><span>or click to browse, paste an image or use the button</span><input type="file" accept="image/jpeg,image/png,image/webp,image/avif" data-file-input hidden><button type="button" class="btn small ghost" data-browse><span class="button-label">Choose image</span></button><div class="upload-status" data-upload-status aria-live="polite"></div></div>
      </div>
    </div>
    <input type="hidden" name="${esc(name)}Source" value="${esc(mode)}">
    <input type="hidden" name="${esc(name)}Id" value="${esc(value.id || '')}">
    <input type="hidden" name="${esc(name)}Url" value="${esc(value.url || '')}">
    <input type="hidden" name="${esc(name)}PublicId" value="${esc(value.publicId || '')}">
    <label class="field media-alt"><span>Image description</span><input name="${esc(name)}Alt" value="${esc(value.alt || '')}" placeholder="What is in the image?"></label>
  </div>`;
}
function menuEditor(items=[]) {
  return `<div class="demo-repeater" id="menuItems">${items.map((item,i)=>menuRow(item,i)).join('')}</div><button type="button" class="btn small ghost" id="addMenuItem">Add menu item</button>`;
}
function menuRow(item,i){
  const p=item||{};
  return `<article class="demo-repeater-row" data-menu-row>
    <div class="row-head"><strong>Item ${i+1}</strong><button type="button" class="text-danger" data-remove-menu>Remove</button></div>
    <div class="form-grid">
      <label class="field"><span>Name</span><input data-menu-field="name" value="${esc(p.name||'')}"></label>
      <label class="field"><span>Price</span><input data-menu-field="price" value="${esc(p.price||'')}"></label>
      <label class="field"><span>Category</span><select data-menu-field="category">${[['Main dishes','Main dishes'],['Sides','Sides'],['Fresh juices','Fresh juices'],['Wine & spirits','Wine & spirits'],['Dessert','Dessert']].map(([v,t])=>`<option value="${v}" ${String(p.category||'Main dishes').toLowerCase()===v.toLowerCase()?'selected':''}>${t}</option>`).join('')}</select></label>
      <label class="field"><span>Currency label</span><input data-menu-field="currency" value="${esc(p.currency||'')}" placeholder="GHS"></label>
      <label class="field wide"><span>Description</span><textarea data-menu-field="description">${esc(p.description||'')}</textarea></label>
      <label class="feature-check"><input type="checkbox" data-menu-field="featured" ${p.featured?'checked':''}><span>Show this dish on the homepage as a popular food</span></label>
      <div class="wide">${imagePicker(`menu_${i}_image`, p.image || {source:'repo',id:repoImages()[0]?.id})}</div>
    </div>
  </article>`;
}
function galleryEditor(items=[]){return `<div class="demo-repeater" id="galleryItems">${items.map((x,i)=>galleryRow(x,i)).join('')}</div><button type="button" class="btn small ghost" id="addGalleryItem">Add gallery image</button>`}
function galleryRow(item,i){return `<article class="demo-repeater-row" data-gallery-row><div class="row-head"><strong>Image ${i+1}</strong><button type="button" class="text-danger" data-remove-gallery>Remove</button></div>${imagePicker(`gallery_${i}_image`, item?.image || {source:'repo',id:repoImages()[0]?.id})}</article>`}
function editorHtml(d,isNew){
  return `<div class="studio-modal">
    <div class="studio-modal-head"><div><p class="eyebrow">Restaurant demo studio</p><h2>${isNew?'Build a new restaurant demo.':`Edit ${esc(d.name || 'restaurant')}.`}</h2><p>Fill the real details, choose the photos and save. The public site and all its pages update from the same record.</p></div></div>
    <form id="demoForm">
      <section class="editor-section"><div class="editor-kicker">1 / Basic details</div>
        <div class="editor-toolbar-line"><span>Most demos can be finished from these fields in a few minutes.</span><button type="button" class="btn small ghost" data-reset-copy="hero">Use starter hero copy</button><button type="button" class="btn small ghost" data-reset-copy="story">Use starter story</button></div>
        <div class="form-grid">
          ${field('Restaurant name *','name',d.name,'required')}${field('Short label','eyebrow',d.eyebrow)}${field('Main line','tagline',d.tagline)}${field('City / area','city',d.city)}${field('Address','address',d.address)}${field('Phone','phone',d.phone)}${field('Public email','email',d.email,'type="email"')}${field('Instagram URL','instagramUrl',d.instagramUrl,'type="url"')}${field('Reservation URL','reservationUrl',d.reservationUrl,'type="url"')}${field('Order URL','orderUrl',d.orderUrl,'type="url"')}${field('Logo text','logoText',d.logoText)}${field('Primary button','primaryCta',d.primaryCta)}${field('Secondary button','secondaryCta',d.secondaryCta)}${textarea('Opening hours','hours',d.hours)}${textarea('Intro','intro',d.intro)}${textarea('Menu page intro','menuIntro',d.menuIntro)}${textarea('Contact page intro','contactIntro',d.contactIntro)}
        </div>
      </section>
      <section class="editor-section"><div class="editor-kicker">2 / Hero</div><div class="media-layout">${imagePicker('heroImage',d.heroImage)}<div><div class="mini-note">Use the strongest photo you have. You can use one of the built-in restaurant images or upload the prospect’s own photo.</div></div></div></section>
      <section class="editor-section"><div class="editor-kicker">3 / Popular foods</div><div class="section-editor-heading"><div><h3>Choose the dishes that sell the page</h3><p>Tick up to three menu items as popular foods. They appear on the homepage. Everything else stays on the full menu page.</p></div></div>${menuEditor(d.menu)}</section>
      <section class="editor-section"><div class="editor-kicker">4 / Our story</div><div class="form-grid">${field('Story title','storyTitle',d.storyTitle)}${textarea('Story copy','storyText',d.storyText)}${field('Experience title','experienceTitle',d.experienceTitle)}${textarea('Experience copy','experienceText',d.experienceText)}<div class="wide">${imagePicker('storyImage',d.storyImage)}</div></div></section>
      <section class="editor-section"><div class="editor-kicker">5 / Gallery</div><div class="section-editor-heading"><div><h3>Restaurant moments</h3><p>Add the room, dishes and atmosphere. Uploading is supported or use one of the built-in images.</p></div></div>${galleryEditor(d.gallery)}<div class="form-grid gallery-copy-fields">${field('Gallery title','galleryTitle',d.galleryTitle)}${textarea('Gallery intro','galleryIntro',d.galleryIntro)}</div></section>
      <section class="editor-section"><div class="editor-kicker">6 / Private dining</div><div class="form-grid">${field('Page title','privateDiningTitle',d.privateDiningTitle)}${field('Guest capacity','privateDiningCapacity',d.privateDiningCapacity)}${textarea('Main copy','privateDiningText',d.privateDiningText)}${textarea('Details / enquiry copy','privateDiningDetails',d.privateDiningDetails)}</div></section>
      <section class="editor-section"><div class="editor-kicker">7 / Visit details</div><div class="form-grid">${field('Dress code','dressCode',d.dressCode)}${field('Parking','parking',d.parking)}${field('Reservation note','reservationNote',d.reservationNote)}</div></section>
      <section class="editor-section"><div class="editor-kicker">8 / Lead details</div><div class="form-grid">${selectField('Lead status','leadStatus',d.leadStatus || (isNew?'New':'Contacted'),[['New','New'],['Contacted','Contacted'],['Replied','Replied'],['Interested','Interested'],['Won','Won'],['Not now','Not now']])}${field('Contact name','recipientName',d.recipientName)}${field('Contact email','recipientEmail',d.recipientEmail,'type="email"')}${textarea('Private note','notes',d.notes)}</div></section>
      <div class="studio-savebar"><div><span class="studio-save-hint">Save first. The public link is created for you.</span><a id="editorPreviewLink" href="${esc(siteDemoUrl(d.slug||slugPreview(d.name)))}" target="_blank" rel="noreferrer">Open preview ${arrowIcon}</a></div><div class="form-actions"><button type="button" class="btn ghost" data-close-modal>Cancel</button><button class="btn dark" type="submit"><span class="button-label">${isNew?'Create demo':'Save changes'}</span></button></div></div>
    </form>
  </div>`;
}
function collectImage(container, prefix){ const source=container.querySelector(`[name="${prefix}Source"]`)?.value || 'repo'; return { source, id: container.querySelector(`[name="${prefix}Id"]`)?.value || '', url: container.querySelector(`[name="${prefix}Url"]`)?.value || '', publicId: container.querySelector(`[name="${prefix}PublicId"]`)?.value || '', alt: container.querySelector(`[name="${prefix}Alt"]`)?.value || '' }; }
function collectForm(form){
  const fd=new FormData(form);
  const d=normalizeDemo({
    name:fd.get('name'),eyebrow:fd.get('eyebrow'),tagline:fd.get('tagline'),intro:fd.get('intro'),city:fd.get('city'),address:fd.get('address'),phone:fd.get('phone'),email:fd.get('email'),hours:fd.get('hours'),
    reservationUrl:fd.get('reservationUrl'),orderUrl:fd.get('orderUrl'),instagramUrl:fd.get('instagramUrl'),logoText:fd.get('logoText'),primaryCta:fd.get('primaryCta'),secondaryCta:fd.get('secondaryCta'),
    menuIntro:fd.get('menuIntro'),contactIntro:fd.get('contactIntro'),storyTitle:fd.get('storyTitle'),storyText:fd.get('storyText'),experienceTitle:fd.get('experienceTitle'),experienceText:fd.get('experienceText'),
    galleryTitle:fd.get('galleryTitle'),galleryIntro:fd.get('galleryIntro'),privateDiningTitle:fd.get('privateDiningTitle'),privateDiningText:fd.get('privateDiningText'),privateDiningDetails:fd.get('privateDiningDetails'),privateDiningCapacity:fd.get('privateDiningCapacity'),dressCode:fd.get('dressCode'),parking:fd.get('parking'),reservationNote:fd.get('reservationNote'),
    leadStatus:fd.get('leadStatus'),recipientName:fd.get('recipientName'),recipientEmail:fd.get('recipientEmail'),notes:fd.get('notes'),heroImage:collectImage(form,'heroImage'),storyImage:collectImage(form,'storyImage')
  });
  d.menu=[...form.querySelectorAll('[data-menu-row]')].map(row=>({
    name:row.querySelector('[data-menu-field="name"]')?.value||'',price:row.querySelector('[data-menu-field="price"]')?.value||'',category:row.querySelector('[data-menu-field="category"]')?.value||'',currency:row.querySelector('[data-menu-field="currency"]')?.value||'',description:row.querySelector('[data-menu-field="description"]')?.value||'',featured:!!row.querySelector('[data-menu-field="featured"]')?.checked,image:collectImage(row,'menu_'+row.dataset.menuIndex+'_image')
  })).filter(x=>x.name||x.description);
  d.gallery=[...form.querySelectorAll('[data-gallery-row]')].map(row=>({image:collectImage(row,'gallery_'+row.dataset.galleryIndex+'_image')})).filter(x=>x.image.id||x.image.url);
  return d;
}
async function cloudinaryUpload(file, statusEl, api){ if(!file) return null; if(!file.type.startsWith('image/')) throw new Error('Please use an image file.'); if(file.size>12*1024*1024) throw new Error('That image is over 12 MB. Please use a smaller file.'); statusEl.textContent='Preparing upload…'; const sig=await api('cloudinarySignature',{}); const endpoint=`https://api.cloudinary.com/v1_1/${sig.cloudName}/image/upload`; return await new Promise((resolve,reject)=>{ const xhr=new XMLHttpRequest(); xhr.open('POST',endpoint); xhr.onload=()=>{ if(xhr.status>=200&&xhr.status<300){try{const d=JSON.parse(xhr.responseText); statusEl.textContent='Uploaded'; resolve({source:'cloudinary',url:d.secure_url,publicId:d.public_id,assetId:d.asset_id,alt:file.name.replace(/\.[^.]+$/,'')});}catch(e){reject(e)}} else { let msg='Cloudinary upload failed.'; try{msg=JSON.parse(xhr.responseText)?.error?.message||msg}catch{} reject(new Error(msg)); } }; xhr.onerror=()=>reject(new Error('The image upload failed. Check your connection and Cloudinary settings.')); xhr.upload.onprogress=e=>{if(e.lengthComputable) statusEl.textContent=`Uploading ${Math.round(e.loaded/e.total*100)}%`;}; const fd=new FormData(); fd.append('file',file); fd.append('api_key',sig.apiKey); fd.append('timestamp',sig.timestamp); fd.append('signature',sig.signature); fd.append('folder',sig.folder); xhr.send(fd); }); }
function bindImageFields(form,api){
  qsa2('.demo-media-field',form).forEach(fieldEl=>{
    if(fieldEl.dataset.mediaReady==='true') return;
    fieldEl.dataset.mediaReady='true';
    const sourceRepo=fieldEl.querySelector('[data-source="repo"]'), sourceUrl=fieldEl.querySelector('[data-source="url"]'), sourceUpload=fieldEl.querySelector('[data-source="cloudinary"]');
    const repoWrap=fieldEl.querySelector('.repo-picker'), urlWrap=fieldEl.querySelector('.url-panel'), uploadWrap=fieldEl.querySelector('.upload-panel'), preview=fieldEl.querySelector('.media-preview');
    const sourceInput=fieldEl.querySelector('input[name$="Source"]'), idInput=fieldEl.querySelector('input[name$="Id"]'), urlInput=fieldEl.querySelector('input[name$="Url"]'), publicIdInput=fieldEl.querySelector('input[name$="PublicId"]');
    const urlField=fieldEl.querySelector('[data-image-url-input]'), useUrl=fieldEl.querySelector('[data-use-url]');
    const fileInput=fieldEl.querySelector('[data-file-input]'), drop=fieldEl.querySelector('[data-dropzone]'), browse=fieldEl.querySelector('[data-browse]'), status=fieldEl.querySelector('[data-upload-status]');
    const setMode=mode=>{sourceInput.value=mode; sourceRepo.classList.toggle('active',mode==='repo'); sourceUrl?.classList.toggle('active',mode==='url'); sourceUpload.classList.toggle('active',mode==='cloudinary'); repoWrap.classList.toggle('hidden',mode!=='repo'); urlWrap?.classList.toggle('hidden',mode!=='url'); uploadWrap.classList.toggle('hidden',mode!=='cloudinary');};
    const pickRepo=id=>{sourceInput.value='repo';idInput.value=id;urlInput.value='';publicIdInput.value='';const r=window.JVO_REPO_IMAGES?.[id];if(r) preview.innerHTML=`<img src="${esc(r.url)}" alt="">`;qsa2('[data-repo-id]',fieldEl).forEach(b=>b.classList.toggle('selected',b.dataset.repoId===id));setMode('repo');};
    const applyUrl=()=>{const url=(urlField?.value||'').trim();if(!/^https:\/\//i.test(url)){toast('Paste a direct https image URL.');return;}sourceInput.value='url';idInput.value='';publicIdInput.value='';urlInput.value=url;preview.innerHTML=`<img src="${esc(url)}" alt="">`;qsa2('[data-repo-id]',fieldEl).forEach(b=>b.classList.remove('selected'));setMode('url');};
    sourceRepo.onclick=()=>setMode('repo'); sourceUrl?.addEventListener('click',()=>setMode('url')); sourceUpload.onclick=()=>setMode('cloudinary');
    qsa2('[data-repo-id]',fieldEl).forEach(b=>b.onclick=()=>pickRepo(b.dataset.repoId)); useUrl?.addEventListener('click',applyUrl); urlField?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();applyUrl();}});
    if(!acceptUpload) return;
    browse.onclick=()=>fileInput.click(); drop.onclick=e=>{if(e.target.closest('button'))return;fileInput.click()};
    ['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('dragover')})); ['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('dragover')}));
    drop.addEventListener('drop',e=>{const f=[...e.dataTransfer.files].find(x=>x.type.startsWith('image/'));if(f)startUpload(f);}); fileInput.addEventListener('change',e=>{const f=e.target.files?.[0];if(f)startUpload(f);});
    fieldEl.addEventListener('paste',e=>{if(uploadWrap.classList.contains('hidden'))return;if(e.target.closest('input:not([type="file"]),textarea,[contenteditable="true"]'))return;const item=[...(e.clipboardData?.items||[])].find(x=>x.type.startsWith('image/'));if(item){e.preventDefault();startUpload(item.getAsFile());}});
    const startUpload=async file=>{try{setMode('cloudinary');busy(browse,true,'Uploading');const result=await cloudinaryUpload(file,status,api);urlInput.value=result.url;publicIdInput.value=result.publicId||'';idInput.value='';sourceInput.value='cloudinary';preview.innerHTML=`<img src="${esc(result.url)}" alt="">`;const alt=fieldEl.querySelector('input[name$="Alt"]');if(alt&&!alt.value)alt.value=result.alt||'';toast('Image uploaded.');}catch(err){status.textContent='Upload failed';notifyError(err);}finally{busy(browse,false);}};
  });
}
function qsa2(s,r){return [...(r||document).querySelectorAll(s)];}
function bindRepeater(form){ qsa2('[data-menu-row]',form).forEach((row,i)=>{row.dataset.menuIndex=i; row.querySelectorAll('[name^="menu_"]')?.forEach(()=>{});}); qsa2('[data-gallery-row]',form).forEach((row,i)=>row.dataset.galleryIndex=i); form.querySelectorAll('[data-remove-menu]').forEach(b=>{if(b.dataset.bound==='true')return;b.dataset.bound='true';b.onclick=()=>{b.closest('[data-menu-row]').remove();refreshIndexes(form);};});form.querySelectorAll('[data-remove-gallery]').forEach(b=>{if(b.dataset.bound==='true')return;b.dataset.bound='true';b.onclick=()=>{b.closest('[data-gallery-row]').remove();refreshIndexes(form);};}); if(form.querySelector('#addMenuItem')?.dataset.bound!=='true'){form.querySelector('#addMenuItem').dataset.bound='true';form.querySelector('#addMenuItem').addEventListener('click',()=>{const wrap=form.querySelector('#menuItems');const idx=wrap.querySelectorAll('[data-menu-row]').length;wrap.insertAdjacentHTML('beforeend',menuRow({name:'',category:'Mains',description:'',price:'',image:{source:'repo',id:repoImages()[0]?.id}},idx));refreshIndexes(form);bindImageFields(form,form._studioApi);bindRepeater(form);});} if(form.querySelector('#addGalleryItem')?.dataset.bound!=='true'){form.querySelector('#addGalleryItem').dataset.bound='true';form.querySelector('#addGalleryItem').addEventListener('click',()=>{const wrap=form.querySelector('#galleryItems');const idx=wrap.querySelectorAll('[data-gallery-row]').length;wrap.insertAdjacentHTML('beforeend',galleryRow({image:{source:'repo',id:repoImages()[0]?.id}},idx));refreshIndexes(form);bindImageFields(form,form._studioApi);bindRepeater(form);});} }
function refreshIndexes(form){qsa2('[data-menu-row]',form).forEach((row,i)=>{row.dataset.menuIndex=i; qsa2('.demo-media-field',row).forEach(m=>{const old=m.dataset.mediaField||''; if(old.startsWith('menu_'))m.dataset.mediaField=`menu_${i}_image`; renameMediaInputs(m,`menu_${i}_image`);});});qsa2('[data-gallery-row]',form).forEach((row,i)=>{row.dataset.galleryIndex=i; qsa2('.demo-media-field',row).forEach(m=>{m.dataset.mediaField=`gallery_${i}_image`;renameMediaInputs(m,`gallery_${i}_image`);});});}
function renameMediaInputs(media,prefix){[['Source',''],['Id',''],['Url',''],['PublicId',''],['Alt','']].forEach(([suffix])=>{const old=[...media.querySelectorAll('input')].find(i=>i.name.endsWith(suffix)); if(old)old.name=prefix+suffix;});}
function bindEditor(d,isNew,api,refresh){openModal(editorHtml(d,isNew));const form=document.querySelector('#demoForm');form._studioApi=api;bindRepeater(form);bindImageFields(form,api);form.querySelectorAll('[data-reset-copy]').forEach(b=>b.onclick=()=>{const starter=defaultTemplate();if(b.dataset.resetCopy==='hero'){form.elements.tagline.value=starter.tagline;form.elements.intro.value=starter.intro;form.elements.eyebrow.value=starter.eyebrow;}if(b.dataset.resetCopy==='story'){form.elements.storyTitle.value=starter.storyTitle;form.elements.storyText.value=starter.storyText;}if(b.dataset.resetCopy==='experience'){form.elements.experienceTitle.value=starter.experienceTitle;form.elements.experienceText.value=starter.experienceText;}});const previewLink=document.querySelector('#editorPreviewLink');const nameInput=form.elements.name;const updatePreview=()=>previewLink.href=siteDemoUrl(slugPreview(nameInput.value));nameInput.addEventListener('input',updatePreview);form.onsubmit=async e=>{e.preventDefault(); const btn=form.querySelector('[type=submit]'); busy(btn,true,isNew?'Creating':'Saving'); try{const payload=collectForm(form); const res=await api(isNew?'createRestaurantDemo':'updateRestaurantDemo',{demoId:d.id,...payload}); closeModal();toast(isNew?'Demo created.':'Demo saved.'); if(res.link) { try {await navigator.clipboard.writeText(res.link); toast(`${isNew?'Demo created.':'Saved.'} Link copied.`);} catch{} } await refresh(); }catch(err){notifyError(err);}finally{busy(btn,false);}};}
function cards(demos){return demos.map(d=>{const status=d.leadStatus||'New';const link=siteDemoUrl(d.slug);return `<article class="demo-card"><div class="demo-card-media">${getImageSrc(d.heroImage)?`<img src="${esc(getImageSrc(d.heroImage))}" alt="" loading="lazy">`:''}<span class="demo-status" data-state="${esc(status)}">${esc(status)}</span></div><div class="demo-card-body"><div><p class="eyebrow">${esc(d.city||'Restaurant concept')}</p><h3>${esc(d.name||'Untitled restaurant')}</h3><p>${esc(d.tagline||'No main line yet.')}</p></div><div class="demo-card-meta"><span>${esc(d.recipientEmail||'No email yet')}</span><span>${d.lastSentAt?`Sent ${new Date(d.lastSentAt).toLocaleDateString('en-GB',{day:'numeric',month:'short'})}`:'Not sent yet'}</span></div><div class="demo-card-actions"><a class="btn small ghost" href="${esc(link)}" target="_blank" rel="noreferrer">Open demo ${arrowIcon}</a><button type="button" class="btn small ghost" data-edit-demo="${esc(d.id)}">Edit</button><button type="button" class="btn small dark" data-email-demo="${esc(d.id)}">Email</button><button type="button" class="icon-btn subtle" title="More" data-more-demo="${esc(d.id)}">•••</button></div></div></article>`}).join('');}
function renderDemos({state,api,refresh,initialTab='demos'}){ window.__JVO_RESTAURANT_STUDIO_TAB__=initialTab||'demos'; const demos=state.restaurantDemos||[]; document.querySelector('#viewRoot').innerHTML=`<section class="studio-hero"><div><p class="eyebrow">JVO / Restaurant demos</p><h2>Build once.<br><em>Personalise fast.</em></h2><p>One restaurant template, one private generator and as many tailored demos as you need. Keep the design consistent, swap the details and send a fresh link.</p></div><div class="studio-hero-actions"><button type="button" class="btn dark" id="newRestaurantDemo"><span>New restaurant</span><span>+</span></button><span class="studio-counter"><strong>${demos.length}</strong> demos saved</span></div></section><div class="studio-tabs"><button type="button" class="active" data-studio-tab="demos">Your demos</button><button type="button" data-studio-tab="email">Outreach email</button><button type="button" data-studio-tab="sent">Sent</button></div><div id="studioTabRoot"></div>`; const tabRoot=document.querySelector('#studioTabRoot'); const showTab=tab=>{window.__JVO_RESTAURANT_STUDIO_TAB__=tab;document.querySelectorAll('[data-studio-tab]').forEach(b=>b.classList.toggle('active',b.dataset.studioTab===tab)); if(tab==='email')renderEmailTab({state,api,refresh,root:tabRoot}); else if(tab==='sent')renderSentTab({state,api,refresh,root:tabRoot}); else renderDemoList({state,api,refresh,root:tabRoot});}; document.querySelector('#newRestaurantDemo').onclick=()=>bindEditor(defaultTemplate(),true,api,refresh);document.querySelectorAll('[data-studio-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.studioTab));showTab(initialTab); }
function renderDemoList({state,api,refresh,root}){ const demos=state.restaurantDemos||[]; root.innerHTML=demos.length?`<div class="demo-grid">${cards(demos)}</div><div class="studio-tip"><strong>Fast workflow</strong><span>Open a demo, replace the hero image if you have one, tweak the copy, save it and send the link. The template stays untouched.</span></div>`:`<div class="studio-empty"><div><span>1</span><strong>No restaurant demos yet.</strong><p>Start with the template. You can be ready to send a first link in a few minutes.</p><button type="button" class="btn dark" id="emptyNewDemo">Build first demo</button></div></div>`; root.querySelector('#emptyNewDemo')?.addEventListener('click',()=>bindEditor(defaultTemplate(),true,api,refresh)); root.querySelectorAll('[data-edit-demo]').forEach(b=>b.onclick=()=>{const d=demos.find(x=>x.id===b.dataset.editDemo); if(d)bindEditor(normalizeDemo(d),false,api,refresh)}); root.querySelectorAll('[data-email-demo]').forEach(b=>b.onclick=()=>{const d=demos.find(x=>x.id===b.dataset.emailDemo); if(d)renderEmailModal(d,state,api,refresh)}); root.querySelectorAll('[data-more-demo]').forEach(b=>b.onclick=()=>openDemoActions(demos.find(x=>x.id===b.dataset.moreDemo),api,refresh));}
function openDemoActions(d,api,refresh){ if(!d)return; openModal(`<div class="quick-actions"><p class="eyebrow">${esc(d.name)}</p><h2>What do you want to do?</h2><a class="btn dark" href="${esc(siteDemoUrl(d.slug))}" target="_blank" rel="noreferrer">Open demo ${arrowIcon}</a><button type="button" class="btn ghost" id="duplicateDemo">Duplicate demo</button><button type="button" class="btn ghost" id="archiveDemo">Archive demo</button><button type="button" class="btn ghost" data-close-modal>Close</button></div>`);document.querySelector('#duplicateDemo').onclick=async()=>{busy(document.querySelector('#duplicateDemo'),true,'Duplicating');try{const res=await api('duplicateRestaurantDemo',{demoId:d.id});closeModal();toast('Demo duplicated.');await refresh();}catch(err){notifyError(err)}finally{busy(document.querySelector('#duplicateDemo'),false)}};document.querySelector('#archiveDemo').onclick=async()=>{if(!confirm(`Archive ${d.name}?`))return;try{await api('archiveRestaurantDemo',{demoId:d.id});closeModal();toast('Demo archived.');await refresh();}catch(err){notifyError(err)}};}
function renderEmailTab({state,api,refresh,root}){
  const demos=state.restaurantDemos||[];
  const saved=state.settings?.restaurantOutreachTemplate||defaultEmail();
  root.innerHTML=`<div class="email-studio">
    <section class="email-editor panel">
      <div class="panel-head"><div><p class="eyebrow">Outreach</p><h2>Send a tailored demo.</h2><p class="panel-sub">Choose a restaurant and the message fills itself in. Change anything before you send it.</p></div></div>
      <div class="email-contact-strip"><div><strong>James Senu</strong><span>CEO, JVO WEB</span></div><a href="https://wa.me/233594121246" target="_blank" rel="noreferrer"><img class="email-wa-icon" src="/images/whatsapp-mark.png" width="20" height="20" alt="WhatsApp"><span>WhatsApp · 0594 121 246</span></a><span class="email-contact-hint">They can also reply to your email.</span></div>
      <form id="outreachForm">
        <div class="form-grid">
          <label class="field wide"><span>Restaurant demo</span><select name="demoId" id="outreachDemo"><option value="">Choose a saved demo</option>${demos.filter(d=>d.leadStatus!=='Not now').map(d=>`<option value="${esc(d.id)}">${esc(d.name)}${d.city?` · ${esc(d.city)}`:''}</option>`).join('')}</select></label>
          <label class="field"><span>Contact name</span><input name="recipientName" value="" placeholder="First name"></label>
          <label class="field"><span>Email address *</span><input name="to" type="email" required placeholder="owner@restaurant.com"></label>
          <label class="field wide"><span>Subject</span><input name="subject" value="${esc(saved.subject||defaultEmail().subject)}"></label>
          <label class="field wide"><span>Email body</span><textarea name="message" id="outreachMessage" class="email-body-editor"></textarea></label>
        </div>
        <div class="variable-row"><span>Insert a detail</span>${['recipientName','restaurantName','city','address','phone','hours','tagline','storyTitle','experienceTitle','demoLink','menuLink','bookingLink','whatsappNumber','whatsappUrl','yourName','businessName'].map(v=>`<button type="button" data-var="{{${v}}}">{{${v}}}</button>`).join('')}</div>
        <div class="email-actions"><button type="button" class="btn ghost" id="saveOutreachTemplate">Save as default template</button><button type="button" class="btn ghost" id="previewOutreach">Preview email</button><button class="btn dark" type="submit"><span class="button-label">Send email</span></button></div>
      </form>
    </section>
    <aside class="email-preview panel" id="emailPreview"><div class="panel-head"><div><p class="eyebrow">Preview</p><h3>What they will receive</h3></div><span class="preview-live">Live</span></div><div id="emailPreviewFrame"></div></aside>
  </div>`;

  const form=root.querySelector('#outreachForm'), demoSelect=form.elements.demoId, message=form.elements.message, preview=root.querySelector('#emailPreviewFrame');
  let currentDemo=null;
  const vars=()=>({recipientName:form.elements.recipientName.value.trim()||'there',restaurantName:currentDemo?.name||'the restaurant',intro:currentDemo?.intro||'',email:currentDemo?.email||'',city:currentDemo?.city||'',address:currentDemo?.address||'',phone:currentDemo?.phone||'',hours:currentDemo?.hours||'',tagline:currentDemo?.tagline||'',eyebrow:currentDemo?.eyebrow||'',storyTitle:currentDemo?.storyTitle||'',experienceTitle:currentDemo?.experienceTitle||'',reservationUrl:currentDemo?.reservationUrl||'',orderUrl:currentDemo?.orderUrl||'',instagramUrl:currentDemo?.instagramUrl||'',demoLink:currentDemo?siteDemoUrl(currentDemo.slug):siteDemoUrl('restaurant'),menuLink:currentDemo?siteDemoUrl(currentDemo.slug)+'/menu':siteDemoUrl('restaurant')+'/menu',bookingLink:currentDemo?siteDemoUrl(currentDemo.slug)+'/booking':siteDemoUrl('restaurant')+'/booking',yourName:'James Senu',businessName:'JVO WEB',whatsappNumber:'0594121246',whatsappUrl:'https://wa.me/233594121246'});
  const fill=template=>{let out=template;Object.entries(vars()).forEach(([k,v])=>out=out.replaceAll(`{{${k}}}`,v));return out;};
  const renderPreview=()=>{preview.innerHTML=emailPreviewHtml(fill(form.elements.message.value||saved.body||defaultEmail().body),fill(form.elements.subject.value||saved.subject||defaultEmail().subject),currentDemo,vars());};
  const loadDemo=()=>{currentDemo=demos.find(d=>d.id===demoSelect.value)||null;form.elements.recipientName.value=currentDemo?.recipientName||'';form.elements.to.value=currentDemo?.recipientEmail||'';message.value=currentDemo?.emailTemplate?.body||saved.body||defaultEmail().body;form.elements.subject.value=currentDemo?.emailTemplate?.subject||saved.subject||defaultEmail().subject;renderPreview();};
  demoSelect.onchange=loadDemo;
  form.addEventListener('input',renderPreview);
  root.querySelectorAll('[data-var]').forEach(b=>b.onclick=()=>{const token=b.dataset.var,start=message.selectionStart||message.value.length;message.setRangeText(token,start,start,'end');message.focus();renderPreview();});
  root.querySelector('#saveOutreachTemplate').onclick=async()=>{try{await api('saveRestaurantEmailTemplate',{subject:form.elements.subject.value,body:message.value});toast('Default email template saved.');}catch(err){notifyError(err);}};
  root.querySelector('#previewOutreach').onclick=()=>emailPreviewHtml(fill(message.value),fill(form.elements.subject.value),currentDemo,vars(),true);
  form.onsubmit=async event=>{event.preventDefault();const btn=form.querySelector('[type=submit]');if(!currentDemo){toast('Choose a restaurant demo first.');return;}busy(btn,true,'Sending');try{await api('sendDemoEmail',{demoId:currentDemo.id,to:form.elements.to.value,recipientName:form.elements.recipientName.value,subject:form.elements.subject.value,message:message.value,idempotencyKey:uid()});toast('Email sent.');await refresh();}catch(err){notifyError(err);}finally{busy(btn,false);}};
  if(demos[0]){demoSelect.value=demos[0].id;loadDemo();}else{message.value=defaultEmail().body;form.elements.subject.value=defaultEmail().subject;renderPreview();}
}
function emailPreviewHtml(body,subject,demo,vars,log=false){
  const d=demo||{name:'Your restaurant',heroImage:{}};const image=getImageSrc(d.heroImage);
  const paragraphs=String(body||'').split(/\n\s*\n/).map(p=>`<p>${esc(p).replace(/\n/g,'<br>')}</p>`).join('');
  const wa='https://wa.me/233594121246';
  const html=`<div class="email-preview-card"><div class="ep-brand"><strong>JVO WEB</strong><span>James Senu · CEO</span></div>${image?`<img class="ep-image" src="${esc(image)}" alt="">`:''}<div class="ep-body"><span class="ep-kicker">A note for ${esc(d.name||'your restaurant')}</span><h4>${esc(subject)}</h4><p class="ep-sender-note">Prepared by James Senu, CEO of JVO WEB.</p>${paragraphs}<a class="ep-button" href="${esc(vars?.demoLink||'#')}" target="_blank" rel="noreferrer">View the concept</a><div class="ep-reach"><span>You can reply to this email</span><a href="${wa}" target="_blank" rel="noreferrer"><img class="ep-wa-icon" src="/images/whatsapp-mark.png" width="18" height="18" alt="WhatsApp"> WhatsApp · 0594 121 246</a></div></div><div class="ep-foot"><strong>JVO WEB</strong><span>James Senu, CEO</span><span>senujames23@gmail.com</span></div></div>`;
  if(log){openModal(`<div class="email-preview-modal"><p class="eyebrow">Email preview</p><h2>${esc(subject)}</h2><div>${html}</div><button type="button" class="btn ghost" data-close-modal>Close</button></div>`);return;}
  return html;
}
function renderEmailModal(d,state,api,refresh){const saved=state.settings?.restaurantOutreachTemplate||defaultEmail();openModal(`<div class="quick-email"><div class="quick-email-top"><div><p class="eyebrow">Outreach email</p><h2>${esc(d.name)}</h2><p>${esc(d.city||'')}</p></div><a href="${esc(siteDemoUrl(d.slug))}" target="_blank" rel="noreferrer">Open demo ${arrowIcon}</a></div><form id="quickEmailForm"><div class="form-grid"><label class="field"><span>Contact name</span><input name="recipientName" value="${esc(d.recipientName||'')}"></label><label class="field"><span>Email address *</span><input name="to" type="email" required value="${esc(d.recipientEmail||'')}" placeholder="owner@restaurant.com"></label><label class="field wide"><span>Subject</span><input name="subject" value="${esc(fillVars(saved.subject||defaultEmail().subject,d,state))}"></label><label class="field wide"><span>Body</span><textarea name="message" class="quick-email-body">${esc(fillVars(saved.body||defaultEmail().body,d,state))}</textarea></label></div><div class="email-actions"><button type="button" class="btn ghost" data-close-modal>Cancel</button><button class="btn dark" type="submit"><span class="button-label">Send email</span></button></div></form></div>`);const form=document.querySelector('#quickEmailForm');form.onsubmit=async e=>{e.preventDefault();const btn=form.querySelector('[type=submit]');busy(btn,true,'Sending');try{await api('sendDemoEmail',{demoId:d.id,to:form.elements.to.value,recipientName:form.elements.recipientName.value,subject:form.elements.subject.value,message:form.elements.message.value,idempotencyKey:uid()});closeModal();toast('Email sent.');await refresh();}catch(err){notifyError(err)}finally{busy(btn,false)}};}
function fillVars(template,d,state){const map={recipientName:d.recipientName||'there',restaurantName:d.name||'the restaurant',intro:d.intro||'',email:d.email||'',logoText:d.logoText||'',city:d.city||'',address:d.address||'',phone:d.phone||'',hours:d.hours||'',tagline:d.tagline||'',eyebrow:d.eyebrow||'',primaryCta:d.primaryCta||'',secondaryCta:d.secondaryCta||'',storyTitle:d.storyTitle||'',experienceTitle:d.experienceTitle||'',reservationUrl:d.reservationUrl||'',orderUrl:d.orderUrl||'',instagramUrl:d.instagramUrl||'',demoLink:siteDemoUrl(d.slug||slugPreview(d.name)),menuLink:siteDemoUrl(d.slug||slugPreview(d.name))+'/menu',bookingLink:siteDemoUrl(d.slug||slugPreview(d.name))+'/booking',yourName:'James Senu',businessName:'JVO WEB',whatsappNumber:'0594121246',whatsappUrl:'https://wa.me/233594121246'};let out=template;Object.entries(map).forEach(([k,v])=>out=out.replaceAll(`{{${k}}}`,v));return out;}
function renderSentTab({state,root}){const rows=(state.emails||[]).filter(e=>e.template==='restaurant_outreach'||e.demoId);root.innerHTML=rows.length?`<section class="panel"><div class="panel-head"><div><p class="eyebrow">Outreach history</p><h2>Sent from the studio.</h2></div><span class="panel-sub">${rows.length} saved</span></div><div class="studio-email-log">${rows.map(e=>`<article><div><span class="eyebrow">${new Date(e.createdAt).toLocaleString('en-GB',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}</span><h3>${esc(e.subject)}</h3><p>To ${esc(e.to)}${e.restaurantName?` · ${esc(e.restaurantName)}`:''}</p></div><a href="${esc(e.demoLink||'#')}" target="_blank" rel="noreferrer">Open demo ${arrowIcon}</a></article>`).join('')}</div></section>`:`<div class="studio-empty"><div><span>1</span><strong>No outreach emails yet.</strong><p>Send from the Outreach email tab and the record will stay here.</p></div></div>`;}
window.JVO_RESTAURANT_STUDIO = { renderDemos };
export { renderDemos };
