(() => {
  const $ = (s, root = document) => root.querySelector(s);
  const $$ = (s, root = document) => [...root.querySelectorAll(s)];
  const esc = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const clean = value => String(value ?? '').trim();
  const CATEGORY_META = [
    {key:'Main dishes', label:'Main dishes', anchor:'main-dishes', desc:'The plates people come for.'},
    {key:'Sides', label:'Sides', anchor:'sides', desc:'The things that belong in the middle.'},
    {key:'Fresh juices', label:'Fresh juices', anchor:'fresh-juices', desc:'Cold, bright and made to order.'},
    {key:'Wine & spirits', label:'Wine & spirits', anchor:'wine-spirits', desc:'A good bottle or a proper pour.'},
    {key:'Dessert', label:'Dessert', anchor:'dessert', desc:'Something sweet before you leave.'}
  ];
  const CATEGORY_ALIASES = {'mains':'Main dishes','main':'Main dishes','main dish':'Main dishes','main dishes':'Main dishes','sides':'Sides','side':'Sides','side dishes':'Sides','drinks':'Wine & spirits','wine':'Wine & spirits','wine & spirits':'Wine & spirits','spirits':'Wine & spirits','bar':'Wine & spirits','juice':'Fresh juices','juices':'Fresh juices','fresh juice':'Fresh juices','fresh juices':'Fresh juices','dessert':'Dessert','desserts':'Dessert'};
  const slugFromLocation = () => { const u = new URL(location.href); if (u.searchParams.get('slug')) return u.searchParams.get('slug'); const p=location.pathname.split('/').filter(Boolean); const i=p.indexOf('restaurant'); return i<0?'':p[i+1]||''; };
  const slug = slugFromLocation();
  const page = document.body.dataset.page || 'home';
  const localHost = ['localhost','127.0.0.1'].includes(location.hostname);
  const pageUrl = (slugValue,target='home') => { const value=encodeURIComponent(slugValue||slug||'restaurant'); if(localHost){const file=target==='home'?'restaurant-demo.html':`restaurant-${target}.html`; return `/${file}?slug=${value}`;} return target==='home'?`/restaurant/${value}`:`/restaurant/${value}/${target}`; };
  const normalizeCategory = value => CATEGORY_ALIASES[clean(value).toLowerCase()] || clean(value) || 'Main dishes';
  const resolveImage = image => { if(!image)return ''; if(typeof image==='string')return /^https?:\/\//i.test(image)?image:(image.startsWith('/')?image:`/${image.replace(/^\/+/,'')}`); if(image.source==='repo'&&image.id){const id=window.JVO_REPO_IMAGES?.[image.id]?image.id:(window.JVO_LEGACY_IMAGE_ALIASES?.[image.id]||image.id);return window.JVO_REPO_IMAGES?.[id]?.url || image.url || '';} if(image.source==='url'&&image.url)return image.url; if(image.source==='cloudinary'&&image.url)return image.url; return image.url||''; };
  const telHref = phone => { const p=String(phone||'').replace(/[^+\d]/g,''); return p?`tel:${p}`:'#'; };
  const safeExternal = value => { try { const u=new URL(String(value||''),location.origin); return ['https:','http:'].includes(u.protocol)?u.href:''; } catch { return ''; } };
  const deepMerge = (base,source) => { const out=JSON.parse(JSON.stringify(base||{})); Object.entries(source||{}).forEach(([k,v])=>{if(v&&typeof v==='object'&&!Array.isArray(v)&&out[k]&&typeof out[k]==='object'&&!Array.isArray(out[k]))out[k]=deepMerge(out[k],v);else out[k]=v;}); return out; };
  function normalizedMenu(items) {
    const template = Array.isArray(window.JVO_RESTAURANT_TEMPLATE?.menu) ? window.JVO_RESTAURANT_TEMPLATE.menu : [];
    const list = Array.isArray(items) ? items.filter(Boolean).map(x=>({...x,category:normalizeCategory(x.category)})) : [];
    if (!list.length) return template.map(x=>({...x,category:normalizeCategory(x.category)}));
    const target=[...list]; const counts=Object.fromEntries(CATEGORY_META.map(c=>[c.key,0])); target.forEach(x=>counts[x.category]=(counts[x.category]||0)+1);
    for(const cat of CATEGORY_META){ const need=Math.max(0, (template.filter(x=>normalizeCategory(x.category)===cat.key).length)-counts[cat.key]); const extras=template.filter(x=>normalizeCategory(x.category)===cat.key).slice(0,need); extras.forEach(ex=>{if(!target.some(x=>x.name===ex.name&&normalizeCategory(x.category)===cat.key))target.push(ex);}); }
    return target;
  }
  async function fetchDemo(){ if(!slug)throw new Error('No restaurant demo was specified.'); const r=await fetch(`/.netlify/functions/api?action=restaurantDemo&slug=${encodeURIComponent(slug)}`,{headers:{accept:'application/json'},cache:'no-store'}); const data=await r.json().catch(()=>({})); if(!r.ok||!data.demo)throw new Error(data.error||'This restaurant demo could not be found.'); const demo=deepMerge(window.JVO_RESTAURANT_TEMPLATE||{},data.demo); demo.menu=normalizedMenu(demo.menu); return demo; }
  const setText=(s,v)=>{const e=$(s);if(e)e.textContent=clean(v);};
  const setHref=(s,v,f='#')=>{const e=$(s);if(e)e.href=v||f;};
  const setTitle=(s,v)=>{const e=$(s);if(!e)return; const words=clean(v).split(/\s+/).filter(Boolean); const split=Math.max(1,Math.ceil(words.length*.58)); e.innerHTML=`${esc(words.slice(0,split).join(' '))}<br><em>${esc(words.slice(split).join(' '))}</em>`;};
  const setImage=(s,img,alt='')=>{const e=$(s);if(!e)return;const src=resolveImage(img);if(!src){e.removeAttribute('src');return;} e.src=src;e.alt=img?.alt||alt;e.loading=e.loading||'lazy';};
  function setupLightbox(){const box=$('#lightbox'),img=$('#lightboxImage'),cap=$('#lightboxCaption'),close=$('#lightboxClose');if(!box||!img||!close)return {open:()=>{}};const hide=()=>{box.classList.remove('is-open');box.setAttribute('aria-hidden','true');document.body.classList.remove('lightbox-open');};const open=(src,alt='')=>{if(!src)return;img.src=src;img.alt=alt;if(cap)cap.textContent=alt;box.classList.add('is-open');box.setAttribute('aria-hidden','false');document.body.classList.add('lightbox-open');close.focus();};close.addEventListener('click',hide);box.addEventListener('click',e=>{if(e.target===box)hide();});document.addEventListener('keydown',e=>{if(e.key==='Escape')hide();});return {open};}
  function bindNavigation(demo){
    const nav=[['Menu',pageUrl(demo.slug,'menu')],['Private dining',pageUrl(demo.slug,'private')],['Gallery',pageUrl(demo.slug,'gallery')],['Contact',pageUrl(demo.slug,'contact')]];
    const desktop=$('#desktopNav');if(desktop)desktop.innerHTML=nav.map(([l,h])=>`<a href="${esc(h)}">${esc(l)}</a>`).join('');
    setHref('#brand',pageUrl(demo.slug,'home'));setText('#brandText',demo.name||'Restaurant');setHref('#headerMenuLink',pageUrl(demo.slug,'menu'));setHref('#headerCta',pageUrl(demo.slug,'booking'));setText('#headerCta','Make a reservation');
    const mobile=$('#mobileNav');
    if(mobile){mobile.innerHTML=`<div class="mobile-nav-head"><span>Explore</span><button type="button" class="mobile-nav-close" id="mobileNavClose">Close</button></div><div class="mobile-nav-links"><a href="${esc(pageUrl(demo.slug,'home'))}">Home</a>${nav.map(([l,h])=>`<a href="${esc(h)}">${esc(l)}</a>`).join('')}<a class="mobile-cta" href="${esc(pageUrl(demo.slug,'booking'))}">Make a reservation</a></div><div class="mobile-nav-foot">${esc(demo.hours||'')}</div>`;}
    const toggle=$('#menuToggle'); if(!toggle||!mobile)return; const closeBtn=$('#mobileNavClose'); const close=()=>{mobile.classList.remove('is-open');mobile.setAttribute('aria-hidden','true');toggle.setAttribute('aria-expanded','false');document.body.classList.remove('nav-open');};const open=()=>{mobile.classList.add('is-open');mobile.setAttribute('aria-hidden','false');toggle.setAttribute('aria-expanded','true');document.body.classList.add('nav-open');}; closeBtn?.addEventListener('click',close);toggle.addEventListener('click',()=>mobile.classList.contains('is-open')?close():open());mobile.addEventListener('click',e=>{if(e.target.closest('a'))close();});document.addEventListener('keydown',e=>{if(e.key==='Escape')close();});
  }
  function renderFooter(demo){setText('#footerBrand',demo.name||'Restaurant');setText('#footerPitch',demo.intro||'Good food, good company and a room worth staying in.');setText('#footerHours',demo.hours||'');const nav=$('#footerNav');if(nav)nav.innerHTML=[['Menu','menu'],['Make a reservation','booking'],['Private dining','private'],['Gallery','gallery'],['Contact','contact']].map(([l,t])=>`<a href="${esc(pageUrl(demo.slug,t))}">${esc(l)}</a>`).join('');setHref('#footerContact',`mailto:${demo.email||''}`,'#');}
  function renderCategoryCarousel(demo){
    const carousel=$('#categoryCarousel');if(!carousel)return;const dots=$('#categoryDots');const menu=normalizedMenu(demo.menu);const cards=CATEGORY_META.map(meta=>{const item=menu.find(x=>normalizeCategory(x.category)===meta.key)||{};return {meta,item};});
    carousel.innerHTML=cards.map(({meta,item})=>`<article class="category-card"><a href="${esc(pageUrl(demo.slug,'menu')+'#'+meta.anchor)}" class="category-card-link" aria-label="View ${esc(meta.label)} in the menu"><div class="category-card-image"><img src="${esc(resolveImage(item.image)||resolveImage(demo.heroImage))}" alt="${esc(item.image?.alt||meta.label)}" loading="lazy"></div><div class="category-card-copy"><span>${esc(meta.label)}</span><h3>${esc(item.name||meta.label)}</h3><p>${esc(meta.desc)}</p><strong>View ${esc(meta.label)}</strong><span class="arrow-icon" aria-hidden="true"></span></div></a></article>`).join('');
    const jumpTo=i=>{const c=$('.category-card',carousel);if(!c)return;const w=c.getBoundingClientRect().width+16;carousel.scrollTo({left:i*w,behavior:'smooth'});};
    if(dots)dots.innerHTML=cards.map((_,i)=>`<button type="button" data-dot="${i}" aria-label="Show category ${i+1}"></button>`).join('');
    $$('#categoryDots button').forEach(b=>b.addEventListener('click',()=>jumpTo(Number(b.dataset.dot||0))));
    const update=()=>{const c=$('.category-card',carousel);if(!c||!dots)return;const w=c.getBoundingClientRect().width+16;const index=Math.round(carousel.scrollLeft/w);$$('button',dots).forEach((b,i)=>b.classList.toggle('active',i===index));};
    carousel.addEventListener('scroll',update,{passive:true}); update();
    let timer=setInterval(()=>{if(document.hidden)return;const c=$('.category-card',carousel);if(!c)return;const w=c.getBoundingClientRect().width+16;const max=Math.max(0,carousel.scrollWidth-carousel.clientWidth);const next=carousel.scrollLeft+w>=max-5?0:carousel.scrollLeft+w;carousel.scrollTo({left:next,behavior:'smooth'});},4200);
    const stop=()=>clearInterval(timer), restart=()=>{clearInterval(timer);timer=setInterval(()=>{const c=$('.category-card',carousel);if(!c)return;const w=c.getBoundingClientRect().width+16;const max=Math.max(0,carousel.scrollWidth-carousel.clientWidth);const next=carousel.scrollLeft+w>=max-5?0:carousel.scrollLeft+w;carousel.scrollTo({left:next,behavior:'smooth'});},4200);};
    carousel.addEventListener('mouseenter',stop);carousel.addEventListener('mouseleave',restart);carousel.addEventListener('touchstart',stop,{passive:true});carousel.addEventListener('touchend',()=>setTimeout(restart,1800),{passive:true});
  }
  function renderHome(demo){
    document.title=demo.name||'Restaurant'; bindNavigation(demo);renderFooter(demo);
    setText('#heroEyebrow',demo.eyebrow||'Kitchen · Bar · Table');setText('#heroName',demo.name||'Restaurant');setText('#heroTagline',demo.tagline||'Dinner worth lingering over.');setImage('#heroImage',demo.heroImage,'Restaurant dining room');setHref('#heroPrimary',pageUrl(demo.slug,'booking'));setText('#heroPrimary','Make a reservation');setHref('#heroSecondary',pageUrl(demo.slug,'menu'));setText('#heroSecondary','View the menu');
    setImage('#introMainImage',demo.storyImage,'A plated dinner');setImage('#introDetailImage',demo.gallery?.[0]?.image,'Dining room');setHref('#introMainLink',pageUrl(demo.slug,'gallery'));setHref('#introDetailLink',pageUrl(demo.slug,'gallery'));setText('#stampCity',demo.city||'');setTitle('#experienceTitle',demo.experienceTitle||'Come for dinner. Stay for the evening.');setText('#experienceText',demo.experienceText||'');setText('#storyPreview',demo.storyText||'');setHref('#storyLink',pageUrl(demo.slug,'gallery'));setText('#factHours',demo.hours||'');setText('#factReservations',demo.reservationNote||'Recommended');setText('#factArrival',demo.dressCode||'Smart casual');
    setImage('#storyImage',demo.storyImage,'Good food, properly served');setText('#storyTitle',demo.storyTitle||'Good food. Properly served.');setText('#storyText',demo.storyText||'');setHref('#storyButton',pageUrl(demo.slug,'menu'));setImage('#barImage',demo.gallery?.[6]?.image,'A drink at the table');setHref('#barLink',pageUrl(demo.slug,'contact'));
    setText('#popularIntro',demo.popularIntro||'Five corners of the menu, from the first plate to the last sweet thing.');setHref('#menuLinkTop',pageUrl(demo.slug,'menu'));renderCategoryCarousel(demo);
    setImage('#eveningImage',demo.gallery?.[3]?.image||demo.heroImage,'A table for two');setText('#eveningIntro',demo.experienceText||'');setHref('#eveningStep1',pageUrl(demo.slug,'menu')+'#fresh-juices');setHref('#eveningStep2',pageUrl(demo.slug,'menu')+'#main-dishes');setHref('#eveningStep3',pageUrl(demo.slug,'menu')+'#wine-spirits');setHref('#eveningCta',pageUrl(demo.slug,'booking'));
    setImage('#privateFeatureImage',demo.gallery?.[2]?.image||demo.heroImage,'Private dining');setText('#privateTeaser',demo.privateDiningText||'');setHref('#privateLink',pageUrl(demo.slug,'private'));
    setText('#arrivalDress',demo.dressCode||'Smart casual.');setText('#arrivalParking',demo.parking||'Street parking nearby.');setText('#arrivalHours',demo.hours||'');setText('#arrivalAddress',demo.address||demo.city||'');setText('#arrivalPhone',demo.phone||'');setHref('#arrivalPhone',telHref(demo.phone));setHref('#arrivalReservation',pageUrl(demo.slug,'booking'));setHref('#arrivalContact',pageUrl(demo.slug,'contact'));
  }
  function itemCard(item){const src=resolveImage(item.image);return `<article class="menu-item"><button class="menu-item-image" type="button" data-menu-image="${esc(src)}" data-menu-alt="${esc(item.image?.alt||item.name)}" aria-label="View ${esc(item.name)} photo">${src?`<img src="${esc(src)}" alt="${esc(item.image?.alt||item.name)}" loading="lazy">`:''}</button><div class="menu-item-copy"><div class="menu-item-top"><h3>${esc(item.name)}</h3><strong>${esc(item.currency||'GHS')} ${esc(item.price||'')}</strong></div><p>${esc(item.description||'')}</p></div></article>`;}
  function renderMenuPage(demo){
    document.title=`${demo.name||'Restaurant'} | Menu`;bindNavigation(demo);renderFooter(demo);setText('#pageEyebrow','The menu');setText('#pageIntro',demo.menuIntro||'A generous menu built for sharing and taking your time.');setText('#menuNote',demo.menuNote||'Sample menu for concept presentation.');setHref('#pageCta',pageUrl(demo.slug,'booking'));setText('#pageCta','Make a reservation');
    const list=$('#menuCategoryList'),filters=$('#menuFilters');if(!list)return;const menu=normalizedMenu(demo.menu);if(filters)filters.innerHTML=CATEGORY_META.map((meta,i)=>`<button type="button" data-filter="${meta.anchor}" class="${i===0?'active':''}">${meta.label}</button>`).join('');
    list.innerHTML=CATEGORY_META.map((meta,idx)=>{const group=menu.filter(x=>normalizeCategory(x.category)===meta.key);return `<section class="menu-category" id="${meta.anchor}"><div class="menu-category-head"><div><span class="eyebrow">${idx+1}</span><h2>${esc(meta.label)}</h2><p>${esc(meta.desc)}</p></div><span class="menu-count">${group.length} items</span></div><div class="menu-list-grid">${group.map(itemCard).join('')}</div></section>`;}).join('');
    setHref('#menuEndCta',pageUrl(demo.slug,'booking'));const box=setupLightbox();$$('[data-menu-image]',list).forEach(b=>b.addEventListener('click',()=>box.open(b.dataset.menuImage,b.dataset.menuAlt)));$$('#menuFilters [data-filter]').forEach(b=>b.addEventListener('click',()=>{b.parentElement.querySelectorAll('button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.filter)?.scrollIntoView({behavior:'smooth',block:'start'});}));
  }
  function renderGalleryPage(demo){document.title=`${demo.name||'Restaurant'} | Gallery`;bindNavigation(demo);renderFooter(demo);setText('#pageEyebrow','The room');setTitle('#pageTitle','A room worth seeing.');setText('#pageIntro',demo.galleryIntro||'');setText('#galleryTitle',demo.galleryTitle||'Take a little look inside.');setText('#galleryIntro',demo.galleryIntro||'');const items=Array.isArray(demo.gallery)?demo.gallery.filter(x=>resolveImage(x.image)):[];const grid=$('#galleryGrid');if(!grid)return;grid.innerHTML=items.map((x,i)=>`<button type="button" data-gallery-index="${i}" aria-label="Open image ${i+1}"><img src="${esc(resolveImage(x.image))}" alt="${esc(x.image?.alt||'Restaurant image')}" loading="lazy"><span>${esc(x.image?.alt||'Restaurant moment')}</span></button>`).join('');const box=setupLightbox();$$('#galleryGrid button').forEach((b,i)=>b.addEventListener('click',()=>box.open(resolveImage(items[i].image),items[i].image?.alt||'')));setHref('#galleryCta',pageUrl(demo.slug,'booking'));setText('#galleryCta','Make a reservation');}
  function renderPrivatePage(demo){document.title=`${demo.name||'Restaurant'} | Private dining`;bindNavigation(demo);renderFooter(demo);setImage('#privateHeroImage',demo.gallery?.[4]?.image||demo.heroImage,'Private dining');setText('#privateHeroIntro',demo.privateDiningText||'');setText('#privateTitle',demo.privateDiningTitle||'Private dinners, done properly.');setText('#privateText',demo.privateDiningText||'');setText('#privateCapacity',demo.privateDiningCapacity||'Up to 30 guests');setText('#privateDetails',demo.privateDiningDetails||'');setHref('#privateHeroCta',pageUrl(demo.slug,'contact'));setHref('#privateCta',pageUrl(demo.slug,'contact'));setHref('#enquirePrimary',pageUrl(demo.slug,'contact'));setHref('#enquirePhone',telHref(demo.phone));}
  function renderContactPage(demo){document.title=`${demo.name||'Restaurant'} | Contact`;bindNavigation(demo);renderFooter(demo);setImage('#contactImage',demo.gallery?.[0]?.image||demo.heroImage,'Restaurant dining room');setText('#contactIntro',demo.contactIntro||'');setText('#contactAddress',demo.address||demo.city||'');setText('#contactHours',demo.hours||'');setText('#contactPhone',demo.phone||'');setHref('#contactPhone',telHref(demo.phone));setText('#contactDress',demo.dressCode||'Smart casual.');setText('#contactParking',demo.parking||'Street parking nearby.');setText('#contactReservation',demo.reservationNote||'Reservations are recommended.');setText('#contactReservation2',demo.reservationNote||'Reservations are recommended.');setHref('#contactPrimary',pageUrl(demo.slug,'booking'));setHref('#contactFinalCta',pageUrl(demo.slug,'booking'));setText('#contactPrimary','Make a reservation');const map=demo.address?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(demo.address)}`:'';setHref('#contactDirections',map);const ig=safeExternal(demo.instagramUrl);const igLink=$('#contactInstagram');if(igLink){igLink.hidden=!ig;if(ig)igLink.href=ig;}}
  function renderBookingPage(demo){document.title=`${demo.name||'Restaurant'} | Make a reservation`;bindNavigation(demo);renderFooter(demo);setImage('#bookingImage',demo.gallery?.[3]?.image||demo.heroImage,'A dinner table');setText('#bookingIntro',demo.reservationNote||'Choose a date, a time and your party size. We will make the rest easy.');setText('#bookingHours',demo.hours||'');setText('#bookingPhone',demo.phone||'');setHref('#bookingPhone',telHref(demo.phone));const date=document.querySelector('input[name="date"]');if(date){const t=new Date();const local=new Date(t.getTime()-t.getTimezoneOffset()*60000).toISOString().slice(0,10);date.min=local;}const form=$('#bookingForm');if(!form)return;form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());const msg=[`Table request for ${demo.name||'Restaurant'}`,'',`Date: ${data.date||''}`,`Time: ${data.time||''}`,`Guests: ${data.guests||''}`,`Occasion: ${data.occasion||'Not specified'}`,'',`Name: ${data.name||''}`,`Email: ${data.email||''}`,`Phone: ${data.phone||''}`,`Notes: ${data.notes||'None'}`].join('\n');const r=safeExternal(demo.reservationUrl), success=$('#bookingSuccess'), successText=$('#bookingSuccessText');if(success)success.hidden=false;if(r){if(successText)successText.textContent='Your details are ready. Continue to the restaurant reservation service to finish.';setTimeout(()=>window.open(r,'_blank','noopener,noreferrer'),150);return;}if(demo.email){const s=encodeURIComponent(`Table request for ${demo.name||'Restaurant'} · ${data.date||''}`),b=encodeURIComponent(msg);if(successText)successText.textContent='Your email app should open with the reservation request ready to send.';setTimeout(()=>location.href=`mailto:${demo.email}?subject=${s}&body=${b}`,150);return;}if(successText)successText.textContent='Please call the restaurant to confirm your request.';});}
  function fail(){document.body.innerHTML='<main class="error-state"><div><span class="eyebrow">Restaurant website</span><h1>This page is not available.</h1><p>The demo link may be incomplete or the saved restaurant could not be loaded.</p><a class="button button-dark" href="/">Back to home</a></div></main>';}
  fetchDemo().then(d=>{if(page==='menu')renderMenuPage(d);else if(page==='gallery')renderGalleryPage(d);else if(page==='private')renderPrivatePage(d);else if(page==='contact')renderContactPage(d);else if(page==='booking')renderBookingPage(d);else renderHome(d);}).catch(error=>{console.error(error);fail(error);});
})();
