const admin=require('firebase-admin');
const crypto=require('crypto');
if(!admin.apps.length){admin.initializeApp({credential:admin.credential.cert({projectId:process.env.FIREBASE_PROJECT_ID,clientEmail:process.env.FIREBASE_CLIENT_EMAIL,privateKey:(process.env.FIREBASE_PRIVATE_KEY||'').replace(/\\n/g,'\n')})})}
const db=admin.firestore();
const json=(statusCode,body)=>({statusCode,headers:{'content-type':'application/json','cache-control':'no-store'},body:JSON.stringify(body)});
const now=()=>new Date().toISOString();
async function user(event){const h=event.headers.authorization||event.headers.Authorization||'';if(!h.startsWith('Bearer '))throw new Error('AUTH');return admin.auth().verifyIdToken(h.slice(7))}
async function adminOnly(event){const u=await user(event);const allowed=(process.env.ADMIN_EMAIL||'senujames23@gmail.com').toLowerCase();if((u.email||'').toLowerCase()!==allowed)throw new Error('FORBIDDEN');return u}
const cleanProject=(id,d)=>({id,...d});
async function activity(projectId,text){await db.collection('activities').add({projectId,text,createdAt:now()})}
async function getSettings(){const d=await db.collection('settings').doc('business').get();return d.exists?d.data():{businessName:'JVO',ownerName:'James Senu',email:'senujames23@gmail.com',phone:'0594121246',snapchat:'jvo_james',supportDays:30,paymentInstructions:'',paymentLink:''}}
async function sendMail({to,subject,message,projectId,projectName}){if(!process.env.RESEND_API_KEY)throw new Error('RESEND_API_KEY is missing.');const from=process.env.RESEND_FROM||'JVO <hello@jvo.me>';const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${process.env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from,to:[to],subject,text:message,reply_to:process.env.REPLY_TO||'senujames23@gmail.com'})});const d=await r.json();if(!r.ok)throw new Error(d.message||'Email could not be sent.');await db.collection('emails').add({to,subject,message,projectId:projectId||'',projectName:projectName||'',resendId:d.id||'',createdAt:now()});return d}
exports.handler=async event=>{try{const action=event.queryStringParameters?.action||'';const body=event.body?JSON.parse(event.body):{};
if(action==='publicProject'){const token=event.headers['x-project-token'];if(!token)return json(400,{error:'Project ID is missing.'});const q=await db.collection('projects').where('publicToken','==',token).limit(1).get();if(q.empty)return json(404,{error:'This project link was not found.'});const doc=q.docs[0],p=doc.data();return json(200,{project:cleanProject(doc.id,{ref:p.ref,projectName:p.projectName,total:p.total,deposit:p.deposit,balance:p.balance,currency:p.currency,timeline:p.timeline,supportDays:p.supportDays,scope:p.scope,features:p.features||[],signedAt:p.signedAt||null,paymentInstructions:p.paymentInstructions||'',paymentLink:p.paymentLink||''})})}
if(action==='sign'){const token=event.headers['x-project-token'];if(!token)return json(400,{error:'Project ID is missing.'});const q=await db.collection('projects').where('publicToken','==',token).limit(1).get();if(q.empty)return json(404,{error:'Project not found.'});const doc=q.docs[0],p=doc.data();if(p.signedAt)return json(409,{error:'This agreement has already been signed.'});for(const k of ['fullName','email','phone','signature'])if(!String(body[k]||'').trim())return json(400,{error:'Please complete all required fields.'});if(String(body.fullName).trim().toLowerCase()!==String(body.signature).trim().toLowerCase())return json(400,{error:'The signature must match the full name.'});const signedAt=now();await doc.ref.update({clientName:String(body.fullName).trim(),clientEmail:String(body.email).trim().toLowerCase(),clientPhone:String(body.phone).trim(),clientCompany:String(body.company||'').trim(),signature:String(body.signature).trim(),signedAt,status:'Awaiting Deposit',updatedAt:signedAt});await activity(doc.id,`Agreement signed by ${String(body.fullName).trim()}`);return json(200,{ok:true})}
await adminOnly(event);
if(action==='adminData'){const [pq,payq,eq,aq,s]=await Promise.all([db.collection('projects').orderBy('createdAt','desc').limit(250).get(),db.collection('payments').orderBy('createdAt','desc').limit(250).get(),db.collection('emails').orderBy('createdAt','desc').limit(100).get(),db.collection('activities').orderBy('createdAt','desc').limit(500).get(),getSettings()]);return json(200,{projects:pq.docs.map(d=>cleanProject(d.id,d.data())),payments:payq.docs.map(d=>cleanProject(d.id,d.data())),emails:eq.docs.map(d=>cleanProject(d.id,d.data())),activities:aq.docs.map(d=>cleanProject(d.id,d.data())),settings:s})}
if(action==='createProject'){if(!body.projectName||!Number(body.total)||!body.scope)return json(400,{error:'Project name, price and scope are required.'});const settings=await getSettings();const seqRef=db.collection('meta').doc('counter');const count=await db.runTransaction(async t=>{const d=await t.get(seqRef),n=(d.exists?d.data().projects||0:0)+1;t.set(seqRef,{projects:n},{merge:true});return n});const year=new Date().getFullYear(),ref=`JVO-${year}-${String(count).padStart(4,'0')}`,total=Number(body.total),deposit=total*.5,token=crypto.randomBytes(18).toString('hex'),createdAt=now();const p={ref,publicToken:token,projectName:String(body.projectName).trim(),total,deposit,balance:total-deposit,amountPaid:0,currency:body.currency||'GHS',timeline:String(body.timeline||'To be agreed').trim(),supportDays:Number(body.supportDays||settings.supportDays||30),liveUrl:String(body.liveUrl||'').trim(),scope:String(body.scope).trim(),features:Array.isArray(body.features)?body.features:[],notes:String(body.notes||'').trim(),status:'Agreement Sent',paymentInstructions:settings.paymentInstructions||'',paymentLink:settings.paymentLink||'',createdAt,updatedAt:createdAt};const doc=await db.collection('projects').add(p);await activity(doc.id,'Project created and agreement link prepared');return json(200,{project:cleanProject(doc.id,p),link:`${process.env.SITE_URL||'https://jvo.me'}/form.html?id=${token}`})}
if(action==='editProject'){const ref=db.collection('projects').doc(body.projectId);const d=await ref.get();if(!d.exists)return json(404,{error:'Project not found.'});const old=d.data(),total=Number(body.total);if(!body.projectName||!total||!body.scope)return json(400,{error:'Project name, price and scope are required.'});const deposit=total*.5;const patch={projectName:String(body.projectName).trim(),total,deposit,balance:total-deposit,timeline:String(body.timeline||'To be agreed').trim(),supportDays:Number(body.supportDays||30),scope:String(body.scope).trim(),features:Array.isArray(body.features)?body.features:[],liveUrl:String(body.liveUrl||'').trim(),notes:String(body.notes||'').trim(),updatedAt:now()};await ref.update(patch);await activity(body.projectId,'Project details updated');return json(200,{project:cleanProject(body.projectId,{...old,...patch})})}
if(action==='recordPayment'){const pr=await db.collection('projects').doc(body.projectId).get();if(!pr.exists)return json(404,{error:'Project not found.'});const p=pr.data(),amount=Number(body.amount);if(!amount||amount<=0)return json(400,{error:'Enter a valid amount.'});const paid=Number(p.amountPaid||0)+amount;let status=p.status;if(body.type==='Deposit')status='Deposit Received';if(paid>=Number(p.total))status='Fully Paid';const createdAt=now();const payment={projectId:pr.id,projectName:p.projectName,clientName:p.clientName||'',clientEmail:p.clientEmail||'',type:body.type||'Payment',amount,currency:p.currency||'GHS',method:body.method||'',reference:body.reference||'',date:body.date||createdAt.slice(0,10),notes:body.notes||'',createdAt};await db.collection('payments').add(payment);await pr.ref.update({amountPaid:paid,status,updatedAt:createdAt});await activity(pr.id,`${payment.type} recorded: ${amount} ${payment.currency}`);return json(200,{ok:true,clientEmail:p.clientEmail||''})}
if(action==='updateProject'){const ref=db.collection('projects').doc(body.projectId);const d=await ref.get();if(!d.exists)return json(404,{error:'Project not found.'});const patch={status:body.status,updatedAt:now()};if(body.status==='Completed')patch.completedAt=now();if(body.status==='Launched')patch.launchedAt=now();await ref.update(patch);await activity(body.projectId,`Project status changed to ${body.status}`);return json(200,{ok:true})}
if(action==='changeRequest'){const p=await db.collection('projects').doc(body.projectId).get();if(!p.exists)return json(404,{error:'Project not found.'});const item={projectId:body.projectId,projectName:p.data().projectName,description:String(body.description||''),amount:Number(body.amount||0),currency:p.data().currency||'GHS',status:body.status||'Quoted',createdAt:now()};await db.collection('changeRequests').add(item);await activity(body.projectId,`Additional work saved: ${item.description} (${item.amount} ${item.currency})`);return json(200,{ok:true})}
if(action==='saveSettings'){await db.collection('settings').doc('business').set({...body,updatedAt:now()},{merge:true});return json(200,{ok:true})}
if(action==='sendEmail'){if(!body.to||!body.subject||!body.message)return json(400,{error:'Email, subject and message are required.'});let projectName='';if(body.projectId){const p=await db.collection('projects').doc(body.projectId).get();projectName=p.exists?p.data().projectName:''}const d=await sendMail({to:body.to,subject:body.subject,message:body.message,projectId:body.projectId,projectName});if(body.projectId)await activity(body.projectId,`Email sent: ${body.subject}`);return json(200,{ok:true,id:d.id})}
return json(404,{error:'Unknown action.'});}catch(e){console.error(e);if(e.message==='AUTH'||e.message==='FORBIDDEN')return json(401,{error:'You are not allowed to do that.'});return json(500,{error:e.message||'Server error.'})}}
